### ISSUE TITLE
bug:getattr(): attribute name must be string

### ISSUE THREAD

**Issue by LeoooooMM** [Junyi42/DiffStyle#1]
I've encountered a mistake in the project like this, which is caused by the outdated version of diffusers. 

`pip install diffusers==0.8.0 instead of 0.3.0`

[[CompVis/stable-diffusion-v1-4 · why bug : getattr(): attribute name must be string? (huggingface.co)](https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/158)](https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/158)

**Comment by Junyi42** [comment]
Thanks for pointing that out! I've updated the `requirements.txt` accordingly.
