### ISSUE TITLE
【Question】代码实现效果问题

### ISSUE THREAD

**Issue by Leaderzhangyi** [Junyi42/DiffStyle#2]
请问作者如何通过代码实现 标题One Model for All Styles中的各个迁移效果呢？也是通过文字依次描述吗？
https://github.com/Junyi42/DiffStyle/blob/6e241e37f125fcfd6f580db6e0172490539bdc38/cartoon_styles.py#L663-L668

**Comment by Junyi42** [comment]
你好，感谢你的关注！是的，正如你引用的代码部分，在这个项目中我们是通过依次更改文字描述实现的。One Model for All Styles的效果主要得益于Stable Diffusion预训练过程中学习到的大量知识。

当然，我们也注意到这种实现方式并不总能得到很好的效果（可以参考[example_results](https://github.com/Junyi42/DiffStyle/tree/main/example_results)中我们得到的部分结果，我们推测这可能是因为clip或者sd在预训练时对于这部分prompt学习得不是很好），建议可以通过修改不同的attention ratio、随机数种子来提升表现。

**Comment by Leaderzhangyi** [comment]
好的 谢谢作者！
